### ISSUE TITLE
Officially dead?

### ISSUE THREAD

**Issue by dmt0** [anorudes/redux-easy-boilerplate#73]
So is this boilerplate being abandoned? Would hate to see it go, it's an awesome project.

**Comment by oltsa** [comment]
I started new job while back and it ate a lot of time. I think that this
project has gone stale. Anorudes was working on new version at some point
but i dont know currently how that is going. As for me Im gonna start
building new boilerplate  soon based on mobx instead of redux. Webpack has
had updates so the configs should be atleast refactored.

**Comment by anorudes** [comment]
@dmt0 Sorry, i don't have enough time to work, buy you can see new boilerplate:
https://github.com/anorudes/redux-universal-boilerplate (but doesn't have components with content)
It'is made from this boilerplate and fully working (used about 3 month in production)

**Comment by anorudes** [comment]
@inertum Interesting. Do you like mobx more than redux? Also like)

**Comment by anorudes** [comment]
Today i will merge both boilerplates in one (this repository) :)
