### ISSUE TITLE
Why are defined constant not used here?

### ISSUE THREAD

**Issue by polarathene** [anorudes/redux-easy-boilerplate#74]
Hello, I was viewing [this file](https://github.com/anorudes/redux-easy-boilerplate/blob/14d80495ba50f2218be9b8fe2b9f738ad185a126/app/redux/modules/app/app.js) and notice you export const to reference strings so they can be used in other classes, but you don't utilize them in the file itself? Why the string dupe?

**Comment by anorudes** [comment]
Hello, @polarathene. In this boilerplates we used [redux-ducks](https://github.com/erikras/ducks-modular-redux) where action creators and reducer in one file. And i think that "defined constants" not need, because need to write more code.  Yes, i know about reducers which use one action, but it's very rarely.
